### ISSUE TITLE
C_mixextend.c: No such file or directory

### ISSUE THREAD

**Issue by kalpeshpatil** [klahnakoski/pymix#2]
I am trying to install pymix from source provided by you. When I try to build usoing "python setup.py build" I get following error "C_mixextend.c: No such file or directory". Any help will be appreciated.

Thanks

**Comment by klahnakoski** [comment]
The setup.py was never updated to install the new version of pymix. I removed the setup.py file so I do not mislead others.  A new setup.py file could be created; this library could be made pip-installable.  

Also, I noticed many fixes were sitting on my local repo without being pushed.  I updated master with some fixes so that all tests pass.
